blocks:
  - white_concrete
  - orange_concrete
  - magenta_concrete
  - light_blue_concrete
  - yellow_concrete
  - lime_concrete
  - pink_concrete
  - gray_concrete
  - light_gray_concrete
  - cyan_concrete
  - purple_concrete
  - blue_concrete
  - brown_concrete
  - green_concrete
  - red_concrete
  - black_concrete
  - oak_slab
  - spruce_slab
  - birch_slab
  - jungle_slab
  - acacia_slab
  - dark_oak_slab
  - stone_slab
  - smooth_stone_slab
  - sandstone_slab
  - cut_sandstone_slab
  - cobblestone_slab
  - brick_slab
  - stone_brick_slab
  - nether_brick_slab
  - quartz_slab
  - red_sandstone_slab
  - cut_red_sandstone_slab
  - purpur_slab
  - prismarine_slab
  - prismarine_brick_slab
  - dark_prismarine_slab
  - polished_granite_slab
  - smooth_red_sandstone_slab
  - polished_diorite_slab
  - end_stone_brick_slab
  - smooth_sandstone_slab
  - smooth_quartz_slab
  - granite_slab
  - andesite_slab
  - polished_andesite_slab
  - diorite_slab
  - red_nether_brick_slab
  - dropper