name: SQSmoothcraft
main: com.spacebeaverstudios.sqsmoothcraft.SQSmoothcraft
version: 1.0
api-version: 1.13
depend:
  - SQCore
commands:
  ship:
    usage: /ship
    description: Commands regarding smoothcraft ships
  release:
    usage: /release
  deletearmorstands:
    usage: /deletearmorstands
    permission: SQSmoothcraft.deletearmorstands
    permission-message: You do not have permission to use this command!
permissions:
  SQSmoothcraft.deletearmorstands:
    default: op
