name: SQSmoothcraft
main: com.spacebeaverstudios.sqsmoothcraft.SQSmoothcraft
version: 1.0
api-version: 1.13
depend:
  - SQCore
commands:
  ship:
    usage: /ship
    description: Commands regarding smoothcraft ships
  release:
    usage: /release
