replicator:
  blockstoitems:
    # wall signs
    OAK_WALL_SIGN: OAK_SIGN
    BIRCH_WALL_SIGN: BIRCH_SIGN
    DARK_OAK_WALL_SIGN: DARK_OAK_SIGN
    JUNGLE_WALL_SIGN: JUNGLE_SIGN
    ACACIA_WALL_SIGN: ACACIA_SIGN
    SPRUCE_WALL_SIGN: SPRUCE_SIGN
  halvecost:
    # doors
    - OAK_DOOR
    - BIRCH_DOOR
    - DARK_OAK_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - SPRUCE_DOOR
    - IRON_DOOR
    # beds
    - BLACK_BED
    - BLUE_BED
    - BROWN_BED
    - CYAN_BED
    - GRAY_BED
    - GREEN_BED
    - LIGHT_BLUE_BED
    - LIGHT_GRAY_BED
    - LIME_BED
    - MAGENTA_BED
    - ORANGE_BED
    - PINK_BED
    - PURPLE_BED
    - RED_BED
    - WHITE_BED
    - YELLOW_BED
  ignore:
    - AIR
    - BEDROCK
    # piston heads
    - MOVING_PISTON
    - PISTON_HEAD
    # multi-block plants because fuck that
    - BAMBOO
    - BAMBOO_SAPLING
    - LARGE_FERN
    - LILAC
    - PETRIFIED_OAK_SLAB # dunno what this is but it's labelled Bisectable
    - ROSE_BUSH
    - SUNFLOWER
    - TALL_GRASS
    - TALL_SEAGRASS