name: SQChat
main: com.spacebeaverstudios.sqchat.SQChat
version: 1.0.0
api-version: "1.15"
loadbefore: [Essentials]
depend: [SQCore, Vault]
commands:
  g:
    description: Puts you into global chat.
  l:
    description: Puts you into local chat.
  p:
    description: Puts you into planet chat.
  tc:
    description: Puts you into town chat.
  nc:
    description: Puts you into nation chat.
  s:
    description: Puts you into staff chat.
    permission: SQChat.staff
    permission-message: You are not staff!
  msg:
    description: Message a player.
  r:
    description: Reply to the last person who messaged you.
  mute:
    description: Mutes a player.
    permission: SQChat.mute
    permission-message: You do not have permission to use this command!
  unmute:
    description: Unmutes a player.
    permission: SQChat.mute
    permission-message: You do not have permission to use this command!
  socialspy:
    description: Sets a player in or out of social spy mode.
    permission: SQChat.socialspy
    permission-message: You do not have permission to use this command!
  jane:
    description: Supercommand for Jane.
    permission: SQChat.jane
    permission-message: You do not have permission to use this command!
permissions:
  SQChat.staff:
    default: op
  SQChat.mute:
    default: op
  SQChat.socialspy:
    default: op
  SQChat.jane:
    default: op